apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-site
  labels:
    app: test-site
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-site
  template:
    metadata:
      labels:
        app: test-site 
    spec:
      containers:
      - name: test-site
        image: nex07/ubnginx-php
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html
            name: nfs-vol
      volumes:
        - name: nfs-vol
          persistentVolumeClaim:
            claimName: nfspvc
