apiVersion: v1
kind: Pod
metadata:
  name: hw-pod
spec:
  restartPolicy: Never
  containers:
  - name: hw
    image: gcr.io/google-samples/node-hello:1.0
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /test
      name: test-vol
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: testpvc
