apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpngx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpngx-test
  template:
    metadata:
      labels:
        app: alpngx-test
    spec:
      containers:
      - name: alpngx-test
        image: nex07/alpngx
        ports:
          - containerPort: 80
