apiVersion: v1
kind: Service
metadata:
   labels:
     app: ng
   name: alpngx-sc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: alpngx-test
  type: LoadBalancer
